### ISSUE TITLE
Use package.json flow

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/engine-tree#11]
https://github.com/jillix/engine-tree/blob/8f3f79009aa2e06d296b50da9e6d9605ecd15b06/server/index.js#L4-L10

**Comment by gabipetrovay** [comment]
What is the `package.json` flow?

**Comment by IonicaBizau** [comment]
@gabipetrovay It's module specific flow. [Here](https://github.com/jillix/engine-terminal/blob/5d86b7e677abe278b6543df35e60136041ca2e23/package.json#L19-L26) is an example.
